### PR TITLE
Reverse playback mode

### PR DESCRIPTION
**Pull request by Xerios**
Ability to reverse the playback + an example.

Not exactly the best way to do this, but this one works most of the time and it's more than good enough for me :)
My first try was trying to use .Reverse() that reversed existing list array and set a boolean value of isReversed to true for all those existing tasks. But doing that meant that I had to duplicate the main loops to support both playback directions and I had few problems with it. So in the end, I thought that nobody would need to reverse a part of the queue, and I rewrote it so that you can only change the general playback direction.

This is just a quick hack, but if you can implement it properly following your code style it would be great :)

Awesome library btw !

### CODE REVIEW

**Comment by alvivar** [comment]
This is a great feature, thank you! I appreciate this a lot.

I will review and test the code as soon as I can, I definitively want this feature on the next stable version!

**Comment by alvivar** [comment]
I just completely merged your code into experimental, I also added some optimizations and a couple of fixes. 

The only relevant change is that I renamed ReversePlayback() BackwardPlayback() and ForwardPlayback() to Reverse() Backward() and Forward(). I'm experimenting with keeping the main API at one simple word.

Also, calling .Reset() (that stops and cleans the queue) and .Release() (that resets the queue modes) will also set the queue to Forward(), to keep things orthogonal.

Your code was at the exact location, clear, easy to read and adapt 😄  Thank you again. 
I still need to do an strong testing to this playback stuff, but it's completely adapted to TeaTime as it is. 

👍

**Comment by alvivar** [comment]
By the way, after fixing some details and testing, the playback modes you made are stable! In fact, I just merged experimental with **master**. TeaTime v0.8.1 is out.

Also, I added a new feature, **.Yoyo()** mode, that will **.Reverse()** the queue when completed. Using it with **.Repeat()** will created an infinite Forward / Backward cycle! Without Repeat Yoyo will go back only once per play!

So cool 👍

**Comment by Xerios** [comment]
Awesome ! Thanks

**Pull request merged**
